{% set name = "Flask-HTTPAuth" %}
{% set version = "3.2.3" %}
{% set sha256 = "5f4ba7ab79103e28b566c6a0592076312d17c716e079c66ca9ffe21a7871ee8d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - flask

test:
  imports:
    - flask_httpauth

about:
  home: http://github.com/miguelgrinberg/flask-httpauth/
  license: MIT
  license_file: LICENSE
  summary: 'Basic and Digest HTTP authentication for Flask routes'
  dev_url: http://github.com/miguelgrinberg/flask-httpauth/
  doc_url: http://flask-httpauth.readthedocs.io

extra:
  recipe-maintainers:
    - synapticarbors
