{% set name = "Flask-HTTPAuth" %}
{% set version = "4.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') | lower }}-{{ version }}.tar.gz
  sha256: 88499b22f1353893743c3cd68f2ca561c4ad9ef75cd6bcc7f621161cd0e80744

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - flask

test:
  requires:
    - python {{ python_min }}
  imports:
    - flask_httpauth

about:
  home: http://github.com/miguelgrinberg/flask-httpauth/
  license: MIT
  license_file: LICENSE
  summary: Basic and Digest HTTP authentication for Flask routes
  dev_url: http://github.com/miguelgrinberg/flask-httpauth/
  doc_url: http://flask-httpauth.readthedocs.io

extra:
  recipe-maintainers:
    - synapticarbors
