{% set name = "Flask-HTTPAuth" %}
{% set version = "3.2.4" %}
{% set sha256 = "f71b7611f385fbdf350e8c430eed17b41c3b2200dc35eae19c1734264b68e31d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - flask

test:
  imports:
    - flask_httpauth

about:
  home: http://github.com/miguelgrinberg/flask-httpauth/
  license: MIT
  license_file: LICENSE
  summary: 'Basic and Digest HTTP authentication for Flask routes'
  dev_url: http://github.com/miguelgrinberg/flask-httpauth/
  doc_url: http://flask-httpauth.readthedocs.io

extra:
  recipe-maintainers:
    - synapticarbors
